services:
  - type: web
    name: adams-call-webrtc
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m server.main
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
    autoDeploy: true
